---
- name: Install base packages
  hosts: all
  become: true
  become_user: root
  
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: latest
        update_cache: yes

    - name: Set hostname
      hostname:
        name: "{{ server_name }}"
    
    # Cài pip và docker để chạy được docker_container module
    - name: Install pip
      apt:
        name: python3-pip
        state: latest

    - name: Install docker pip
      pip:
       name: docker